### ISSUE TITLE
Connection not established 10-28 09:56:07.601 32714-400/com.example.nvan.myapplication E/EWS: microsoft.exchange.webservices.data.EWSHttpException

### ISSUE THREAD

**Issue by VictorJava** [vanan08/AndroidExchange-EWS-#1]
Hi vanan08, 

I trying to use your library.
I need to read messages.
There is code which I used in TestEWS:
![crash_vanan08](https://cloud.githubusercontent.com/assets/8449621/10782622/9a1a79ae-7d5a-11e5-8288-f9d5e48a48a1.png)

Please, could you help me?

**Comment by cmcdev2015** [comment]
Pls check your microsoft exchange version, maybe it's not Exchange2007_SP1

**Comment by vanan08** [comment]
You should check microsoft exchange version on your mail server(Ask your admin), maybe it's not Exchange2007_SP1.
Some versions supported:
- Microsoft Exchange 2007, Service Pack 1: Exchange2007_SP1
- Microsoft Exchange2010: Exchange2010
- Microsoft Exchange 2010, Service Pack 1:  Exchange2010_SP1
- Microsoft Exchange 2010, Service Pack 2:  Exchange2010_SP2
  
  ExchangeService service = new ExchangeService(ExchangeVersion.Exchange2007_SP1);
